apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-db-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      volumes:
        - name: todo-db-volume
          persistentVolumeClaim:
            claimName: todo-db-claim
      containers:
      - name: todo-db
        image: todo-db:v1.0
        env:
        - name: POSTGRES_PASSWORD
          value: "12345"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: todo-db-volume
          mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: todo-db-service
spec:
  selector:
    app: todo-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
