apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api
        image: todo-api:v1.0
        ports:
        - containerPort: 3001
        env:
          - name: DB_HOST
            value: "todo-db-service.default.svc.cluster.local"
          - name: DB_PASSWORD
            value: "12345"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-api-service
spec:
  type: NodePort
  selector:
    app: todo-api
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 30001
